Modifications for Arduino 1.x
mgreensmith/deltabot pull request #1
Opened 2016-11-21 13:48 UTC by todocono

For this version, I just changed the methods of ControlP5 and modified small details like pins and added a Serial print for clarity.

2016-11-21 22:46 UTC, mgreensmith requested changes
Thanks for this PR, I'm excited to see that people are using this code.

With that said, this PR looks like a combination of user-specific changes that you made for yourself, along with some ControlP5 bugfixes for compatibility.

To preserve compatibility for existing users, I would not merge an unnecessary folder/file name change.

Also, sorry but I won't merge your new authorship attribution. You're not rewriting, substantially changing, or even adding new features to this project. Changing the value of a constant does not make you an author. Frankly, it's upsetting to me that you added this attribution in your fork, and you're presenting this project as authored by you in your NYU coursework blog. That's pretty dishonest.

I would definitely be willing to merge the API changes for ControlP5, if you'd provide those as a separate commit. Thanks for that work.

2016-11-21 22:46 UTC, mgreensmith commented on deltabot_Arduino/deltabot_Arduino.ino
> + * Latest version  0.3 by Rudi Cossovich
Sorry, but renaming the file and changing pin assignments does not merit an authorship change.

2016-11-21 22:46 UTC, mgreensmith commented on deltabot_Arduino/deltabot_Arduino.ino
> +int SERVO_3_PIN = 10;
Changing these will break compatibility with anyone else currently using this code.

2016-11-21 22:46 UTC, mgreensmith commented on deltabot_Processing/deltabot_Processing.pde
> +  myPort = new Serial(this, Serial.list()[2], 9600);
Changing this will break compatibility. Maybe move it up to a top-level constant and then it'll be easier for people to find and configure.

2016-11-21 22:46 UTC, mgreensmith commented on deltabot_Processing/deltabot_Processing.pde
> +  //controlP5.setColorLabel(0xff000000);
Accidentally-committed?

2016-11-22 01:09 UTC, todocono commented
Woooow... slow down a minute.. I am a hardware guy with no formal formation
on software. I thought that I was following the formal protocol of updating
a piece of code and sharing the changes. You called v0.2 and y called it
v0.3. In the same way that you mentioned previous authors and license
model, I did the same. If the instructions are within a courseware given at
university, I don't see how does somehow become a discredit to you or to
the code.

You could help to rewrite the licensing part that makes you upset, if you
wish to. If not, disregard the code as it seems you will. If I was trying
to remotely be dishonest, I would not have gone through the pain of doing a
pull request. This was my first and, most likely, last pull request given
to this experience.

About the code changes, pins and the specific serial port, you are right. I
didn't think about that. But naming convention is needed among folder/file
on both IDEs to compile, no workaround that.

2016-11-22 6:46 GMT+08:00 Matt Greensmith <notifications@github.com>:

> *@mgreensmith* requested changes on this pull request.
>
> Thanks for this PR, I'm excited to see that people are using this code.
>
> With that said, this PR looks like a combination of user-specific changes
> that you made for yourself, along with some ControlP5 bugfixes for
> compatibility.
>
> To preserve compatibility for existing users, I would not merge an
> unnecessary folder/file name change.
>
> Also, sorry but I won't merge your new authorship attribution. You're not
> rewriting, substantially changing, or even adding new features to this
> project. Changing the value of a constant does not make you an author.
> Frankly, it's upsetting to me that you added this attribution in your fork,
> and you're presenting this project as authored by you in your NYU
> coursework blog. That's pretty dishonest.
>
> I would definitely be willing to merge the API changes for ControlP5, if
> you'd provide those as a separate commit. Thanks for that work.
> ------------------------------
>
> In deltabot_Arduino/deltabot_Arduino.ino
> <https://github.com/mgreensmith/deltabot/pull/1#pullrequestreview-9558037>
> :
>
> > @@ -1,27 +1,31 @@
>  /*
> - * deltabot_servos.pde
> - * Created by Matt Greensmith, 25 May 2011
> - * version 0.2
> - * Last edit: 25 November 2011
> + * deltabot_Arduino.ino
> + * Latest version  0.3 by Rudi Cossovich
>
> Sorry, but renaming the file and changing pin assignments does not merit
> an authorship change.
> ------------------------------
>
> In deltabot_Arduino/deltabot_Arduino.ino
> <https://github.com/mgreensmith/deltabot/pull/1#pullrequestreview-9558037>
> :
>
> >   *
>   */
>
>  // Import the Arduino Servo library
>  #include <Servo.h>
>
>  // Physical pins where servos will be attached.
> -int SERVO_1_PIN = 9;
> -int SERVO_2_PIN = 10;
> -int SERVO_3_PIN = 11;
> +int SERVO_1_PIN = 8;
> +int SERVO_2_PIN = 9;
> +int SERVO_3_PIN = 10;
>
> Changing these will break compatibility with anyone else currently using
> this code.
> ------------------------------
>
> In deltabot_Processing/deltabot_Processing.pde
> <https://github.com/mgreensmith/deltabot/pull/1#pullrequestreview-9558037>
> :
>
> > @@ -76,12 +76,12 @@ Slider servo3;
>
>  void setup() {
>    //open serial connection
> -  myPort = new Serial(this, Serial.list()[0], 9600);
> +  myPort = new Serial(this, Serial.list()[2], 9600);
>
> Changing this will break compatibility. Maybe move it up to a top-level
> constant and then it'll be easier for people to find and configure.
> ------------------------------
>
> In deltabot_Processing/deltabot_Processing.pde
> <https://github.com/mgreensmith/deltabot/pull/1#pullrequestreview-9558037>
> :
>
> >
>    size(300,600);
>    frameRate(25);
>    controlP5 = new ControlP5(this);
> -  controlP5.setColorLabel(0xff000000);
> +  //controlP5.setColorLabel(0xff000000);
>
> Accidentally-committed?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/mgreensmith/deltabot/pull/1#pullrequestreview-9558037>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AA75PmrBlSZZx2dXkivMRzka9YVmhrd1ks5rAh8wgaJpZM4K4OFX>
> .
>

2016-11-22 03:16 UTC, mgreensmith commented
Gosh, ok, apologies. Let's start again, with an assumption of good faith, and we'll see if we can turn this experience around for both of us.

When I clicked the link to your fork of this project, from http://ima.nyu.sh/animatronics/, I was greeted by my/your [README](https://github.com/todocono/deltabot/blob/master/README), into which you had placed your name as the author (separate from your attribution addition to `deltabot_Ardunio.ino`). It honestly looked to me as though you were trying to take credit for this project. Apologies for overreacting.

You're right that the license/versioning could be better. This is actually my first published project, and the comments in the code pre-date the use of git/github for distribution.

I think it's time to make this codebase into a proper open-source release, rather than a glorified dump of old code. Give me a little time to push a few changes, either into this PR or a new branch, to add an appropriate license, changelog and readme. With that done, I'll be comfortable merging these changes.

Thanks for understanding, and please don't give up on contributing to open source projects.

2016-11-22 03:24 UTC, todocono commented
Ah, you made my morning. I was pretty obfuscated by putting time and effort
but getting a harsh comment. I apology as well, now that I read the
readme.md it does not reflect the project.

As you said, it is a compilation of different patches instead of a cohesive
version. Please let me know when you push a newer version. I think I can
also post pictures on the actual building / dimensions / materials. I have
quite a bit of experience on that.

2016-11-22 11:16 GMT+08:00 Matt Greensmith <notifications@github.com>:

> Gosh, ok, apologies. Let's start again, with an assumption of good faith,
> and we'll see if we can turn this experience around for both of us.
>
> When I clicked the link to your fork of this project, from
> http://ima.nyu.sh/animatronics/, I was greeted by my/your README
> <https://github.com/todocono/deltabot/blob/master/README>, into which you
> had placed your name as the author (separate from your attribution addition
> to deltabot_Ardunio.ino). It honestly looked to me as though you were
> trying to take credit for this project. Apologies for overreacting.
>
> You're right that the license/versioning could be better. This is actually
> my first published project, and the comments in the code pre-date the use
> of git/github for distribution.
>
> I think it's time to make this codebase into a proper open-source release,
> rather than a glorified dump of old code. Give me a little time to push a
> few changes, either into this PR or a new branch, to add an appropriate
> license, changelog and readme. With that done, I'll be comfortable merging
> these changes.
>
> Thanks for understanding, and please don't give up on contributing to open
> source projects.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/mgreensmith/deltabot/pull/1#issuecomment-262136593>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AA75PizYAeR4ecshad2p4twaJqbyrDn_ks5rAl51gaJpZM4K4OFX>
> .
>

2016-11-22 05:39 UTC, merged

2016-11-22 05:58 UTC, mgreensmith commented
OK, I made a number of changes in https://github.com/mgreensmith/deltabot/pull/2, specifically adding a proper license ad headers, adding a change log, and improving the readme.

I've set up github tags/releases now, so I was able to create a release of the old version of the code for people that need to maintain compatibility. This means that I could merge all of your changes (file renames, pinout changes) and release version 0.3.0 of this project. You are credited in the change log.

Please merge my `master` branch into your forked copy so that you have these changes, or, if you're willing, point your NYU blog post link to this repo rather than the forked copy.

Thanks!

2016-11-22 06:01 UTC, todocono commented
Ha ! we definitively turned a bad experience into a meaningful
collaboration.

I will point the blog to your repo and keep you posted if anybody comes
with ideas to improve the code.

2016-11-22 13:58 GMT+08:00 Matt Greensmith <notifications@github.com>:

> OK, I made a number of changes in #2
> <https://github.com/mgreensmith/deltabot/pull/2>, specifically adding a
> proper license ad headers, adding a change log, and improving the readme.
>
> I've set up github tags/releases now, so I was able to create a release of
> the old version of the code for people that need to maintain compatibility.
> This means that I could merge all of your changes (file renames, pinout
> changes) and release version 0.3.0 of this project. You are credited in the
> change log.
>
> Please merge my master branch into your forked copy so that you have
> these changes, or, if you're willing, point your NYU blog post link to this
> repo rather than the forked copy.
>
> Thanks!
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/mgreensmith/deltabot/pull/1#issuecomment-262154918>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AA75PrZiZBFQFlVPI1sbP_9HhoP7NihZks5rAoRwgaJpZM4K4OFX>
> .
>